# Navigation
nav:
- Home:
  - 'index.md'
  - 'why_software.md'
- Setup:
  - 'setup/3rd_party_libs.md'
- Version Control:
  - 'version_control/BasicGit.md'
  - 'version_control/GitWorkflow.md'
  - 'version_control/github.md'
- Java Fundamentals:
  - 'basics/java_types_variables.md'
  - 'basics/java_methods.md'
  - 'basics/java_classes.md'
  - 'basics/java_control_flow.md'
- FRC Background:
  - 'basics/roboRIO.md'
  - 'basics/sensors.md'
  - 'basics/wpilib.md'
  - 'basics/ElectronicsCrashCourse.md'
  - 'basics/vscode_tips.md'
  # - 'basics/driverstation_tips.md'
- FRC Development Environment Setup:
  - 'setup/install_software.md'
  - 'setup/install_other.md'
  - 'setup/imaging_roboRIO.md'
- FRC Programming:
  - 'programming/new_project.md'
  - 'programming/driving_robot.md'
  - 'programming/deploying.md'
  - 'programming/using_sensors.md'
  - 'programming/pneumatics.md'
  - 'programming/Elastic.md'
  - 'programming/robotpreferences.md'
  - 'programming/autonomous.md'
  - 'programming/pid.md'
  - 'programming/AdvantageKit.md'
  - 'programming/AKitStructureReference.md'
  # - 'programming/super_core.md'
- Example Subsystems:
  - 'examples/basic_elevator.md'
  - 'examples/basic_shooter.md'
  - 'examples/pid_elevator.md'
  - 'examples/pid_shooter.md'

- Improve the Documentation:
  - 'contributing.md'

# Setup
site_name: FRC Java Programming
repo_name: Tutorial Bot
repo_url: https://github.com/RoboLancers/FRC-Java-Tutorial/tree/main
edit_uri: https://github.com/RoboLancers/FRC-Java-Tutorial/edit/main/docs/
site_author: Tayler Uva, Carl Stanton

# Theme
theme:
  name: 'material'
  favicon: assets/favicon.png
  #icon:
  #  logo: assets/favicon.png
  features:
    - content.tabs.link
    - content.code.copy
use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.blocks.tab
  - pymdownx.betterem
  - pymdownx.tasklist
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: ["."]
  - toc:
      permalink: "#"

# Plugins
plugins:
  - search
  - mkdocs_quiz
  # - minify:
  #     minify_html: true
  #     minify_js: true
