name: Autograder

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  autograder:
    name: Run Autograder
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run autograder
        uses: education/autograding@v1
